name: PR naming trigger

on:
  pull_request:

jobs:
  pr-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@v1.2.0
        with: 
          title-regex: '^TAU-\d+.+'
          error-message: 'You must start the PR with TAU-'
    
    
